[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install && npm run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = [
    "netlify/functions/likes.json"
  ]

[build.environment]
  FORCE_IPV4 = "true"
  NODE_VERSION = "18"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://adembayazit.com"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    X-NF-Client-Connection-IP = ":client-ip"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
