[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/*.js"]
  included_files = ["netlify/functions/*.js", "package.json"]
  included_files = ["netlify/functions/likes.json"]
[build.environment]
  FORCE_IPV4 = "true"
  NODE_VERSION = "18"
[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = 
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    X-NF-Client-Connection-IP = ":client-ip"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
